GET http://localhost:8080/todos/all HTTP/1.1

###

POST http://localhost:8080/todos/add HTTP/1.1
Content-Type: "application/x-www-form-urlencoded"

###
PUT http://localhost:8080/todos/update  HTTP/1.1
content-type: application/json


###

DELETE http://localhost:8080/todos/delete  HTTP/1.1

###

PUT http://localhost:8080/todos/complete/1 HTTP/1.1
content-type: application/json

###
PUT http://localhost:8080/todos/uncomplete/1 HTTP/1.1
content-type: application/json